name: "install-minio"
description: "Install MinIO Client and Server on Different Platforms"

runs:
  using: "composite"
  steps:
  - name: Install Minio Server and Client on Windows
    if: runner.os == 'Windows'
    run: |
      choco install minio-server minio-client
  - name: Install Minio Server and Client on MacOS
    if: runner.os == 'macOS'
    run: |
      brew install minio minio-mc
  - name: Install Minio Server and Client on Ubuntu
    if: runner.os == 'Linux'
    run: |
      wget https://dl.min.io/server/minio/release/linux-amd64/minio
      chmod +x minio
      sudo mv minio /usr/local/bin
      wget https://dl.min.io/client/mc/release/linux-amd64/mc
      chmod +x mc
      sudo mv mc /usr/local/bi
